# Generated by Django 6.0.4 on 2026-04-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='phone_numbers',
            field=models.CharField(default=(2816861001, 2816861001), max_length=5000),
            preserve_default=False,
        ),
    ]
