# Generated by Django 6.0.4 on 2026-04-25 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glow', '0002_room_phone_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
    ]
