# Generated by Django 6.0.4 on 2026-04-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glow', '0004_room_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
